# Generated by Django 4.2.2 on 2023-06-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('name', models.TextField()),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
