# Generated by Django 4.2.2 on 2023-06-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_rename_datetimefield_input_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='time',
            new_name='datetime_field',
        ),
    ]
