# Generated by Django 4.2.2 on 2023-06-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_rename_time_input_datetime_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='description',
            field=models.TextField(max_length=350),
        ),
    ]
