# Generated by Django 4.2.2 on 2023-06-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0006_alter_input_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='description',
            new_name='address',
        ),
    ]
